### ISSUE TITLE
Feature Request - Store Settings (i.e. line colours) in SnakeTail.exe.config or allow Import/Export

### ISSUE THREAD

**Issue by mmiddleton3301** [snakefoot/snaketail-net#106]
Firstly, just wanted to say, thank you for putting together such a top utility :) I use it often as a developer to parse through my log files. This is great on my development environment and on servers where my software is deployed. I love the line highlighting/colouring.

A suggestions/request:
Could you store line colour settings in the application `.config file` rather than in the XML file in `C:\ProgramData\SnakeTail`? If you stored the line colours `SnakeTail.exe.config`, I could then zip up the application and config and easily move it from machine to machine. Or maybe provide an option to?

Another alternative way to approach this would be to store `SnakeTail.xml` in the same directory as the application.

If the above isn't possible then maybe an option to export/import the settings? :)

**Comment by snakefoot** [comment]
You can create a default config file for SnakeTail, by opening a file and setup all the stuff you like, and then save the file as SnakeTail.xml next to the SnakeTail.exe.

Then when SnakeTail.exe opens a new file, then it will apply the default-config found in SnakeTail.xml. See also:

http://snakenest.com/2011/snaketail-ver-1-3-released/

**Comment by mmiddleton3301** [comment]
@snakefoot Perfect, I wasn't aware of this. Thank you for taking your time to reply :)
