### ISSUE TITLE
Exception occurs when checking for updates

### ISSUE THREAD

**Issue by GoApplicateTCJ** [snakefoot/snaketail-net#117]
An exception occurs when checking for updates in version 1.9.4.0

![billede](https://user-images.githubusercontent.com/20090284/41409971-51e0839a-6fd8-11e8-97ac-ea56e12080fe.png)

The exception reads:

Application does not support just-in-time (JIT)
debugging. See the end of this message for details.

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.HttpWebRequest.GetResponse()
   at SnakeTail.CheckForUpdates.SendReport(CrashReportDetails crashReport) in D:\PERSONAL\Documents\Visual Studio Projects\snaketail-net.2\SnakeTail\ThreadExceptionDialogEx.cs:line 294
   at SnakeTail.MainForm.checkForUpdateToolStripMenuItem_Click(Object sender, EventArgs e) in D:\PERSONAL\Documents\Visual Studio Projects\snaketail-net.2\SnakeTail\MainForm.cs:line 734

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3101.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SnakeTail
    Assembly Version: 1.9.4.0
    Win32 Version: 1.9.4.0
    CodeBase: file:///C:/Program%20Files/SnakeTail/SnakeTail.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3101.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------

************** JIT Debugging **************
Application does not support Windows Forms just-in-time (JIT)
debugging. Contact the application author for more
information.

**Comment by snakefoot** [comment]
Looks like the WebHost had implemented some hardcore security check. So when failing to provide some random UserAgent, then request would be rejected with "HTTP Error 406 Not acceptable - Security incident detected"

**Comment by Scrivener07** [comment]
Same for me. Using version 1.9.4, Selecting 'Help >About' causes an unhandled exception.

`The remote server returned an error: (406) Not Acceptable.`
```
Application does not support just-in-time (JIT)
debugging. See the end of this message for details.

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (406) Not Acceptable.
   at System.Net.HttpWebRequest.GetResponse()
   at SnakeTail.CheckForUpdates.SendReport(CrashReportDetails crashReport) in D:\PERSONAL\Documents\Visual Studio Projects\snaketail-net.2\SnakeTail\ThreadExceptionDialogEx.cs:line 294
   at SnakeTail.MainForm.checkForUpdateToolStripMenuItem_Click(Object sender, EventArgs e) in D:\PERSONAL\Documents\Visual Studio Projects\snaketail-net.2\SnakeTail\MainForm.cs:line 734


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SnakeTail
    Assembly Version: 1.9.4.0
    Win32 Version: 1.9.4.0
    CodeBase: file:///C:/Program%20Files/SnakeTail/SnakeTail.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
Application does not support Windows Forms just-in-time (JIT)
debugging. Contact the application author for more
information.
```

**Comment by timjen3** [comment]
I see a fix has been merged into master. Here's the fix from June 19, 2018:
https://github.com/snakefoot/snaketail-net/commit/5d98b0168376b46ef528363b2f0046a392f51019

There are some other recent commits, I wonder if there is a reason for no releases since Aug 17, 2016 aside from lack of time?

**Comment by snakefoot** [comment]
Have now released ver. 1.9.5
