### ISSUE TITLE
Configuration Settings

### ISSUE THREAD

**Issue by RegencySoftware** [snakefoot/snaketail-net#119]
How do you export / save the configuration settings (colors, and so forth) so you can move to another machine. When I save the config file still only contains the .NET settings. I scanned appdata folder but do not see a setting file there either. 

Thank you

**Comment by snakefoot** [comment]
This might help you solve the quest:


http://snakenest.com/2011/snaketail-ver-1-3-released/


Sent from my Samsung device


-------- Original message --------
