### ISSUE TITLE
Recent Files menu is empty after application restart

### ISSUE THREAD

**Issue by adevaykin** [snakefoot/snaketail-net#123]
Reproduce:
1. Open a session file in SnakeTail
2. Check that this file is present in menu File -> Recent Files
3. Close Snake Tail
4. Start SnakeTail again
5. Menu File -> Recent Files is empty
Expected: recent files are listed there.

Thank you for supporting a great tool!

**Comment by snakefoot** [comment]
Have you marked the menu item to save it in windows registry?

Sent from my Sony Xperia


---- adevaykin wrote ----


Reproduce:

  1.  Open a session file in SnakeTail
  2.  Check that this file is present in menu File -> Recent Files
  3.  Close Snake Tail
  4.  Start SnakeTail again
  5.  Menu File -> Recent Files is empty
Expected: recent files are listed there.

Thank you for supporting a great tool!

**Comment by adevaykin** [comment]
Okay now when I did it it worked well. Thank you!
Although I find it a bit confusing. I've never seen such an option in applications - usually recent files are simply there where you expect them to be... Maybe have this checkbox checked by default?

**Comment by snakefoot** [comment]
Geeky people don't like applications doing messy stuff in the registry

Sent from my Sony Xperia


---- adevaykin wrote ----


Okay now when I did it it worked well. Thank you!
Although I find it a bit confusing. I've never seen such an option in applications - usually recent files are simply there where you expect them to be... Maybe have this checkbox checked by default?
