### ISSUE TITLE
Allow Manual Reloading

### ISSUE THREAD

**Issue by mojomojomojo** [snakefoot/snaketail-net#126]
It would be convenient if I were able to manually reload a file via a context-sensitive menu or something.

I use SnakeTail to monitor some files that are not append-only log files, and I'd like to be able to "refresh" them manually. At the moment (1.9.4—I haven't tried 1.9.5, though the changelog doesn't suggest any change in this behavior), I have to close the file and open it again, which is inconvenient.

**Comment by snakefoot** [comment]
I have added a new menu-item called "Reopen File" with shortcut-key CTRL + R. It will make the window save its current config in memory and reload from scratch.

**Comment by snakefoot** [comment]
Version 1.9.6 have been released.

**Comment by RvdHout** [comment]
Hello @snakefoot 

is this change actually working?  eg: I have a file opened, but if manually change something, like the order of some lines in that file and then choose "Reopen File" or use shortcut-key CTRL + R nothing seems to happen, it still shows the old lines in their initial order and are not updated with my manually made changes (using Version 1.9.8)

**Comment by snakefoot** [comment]
@RvdHout No idea. It worked when I developed it. You are welcome to take another look, and see if something can be improved.
