### ISSUE TITLE
Recent Files list not storing file name in version 1.9.5

### ISSUE THREAD

**Issue by stuartbrownfarmote** [snakefoot/snaketail-net#128]
The "Recent Files" feature worked in version 1.9.4. Updated to 1.9.5 and this feature no longer works.

Running Windows 10, with save to registry selected. Full path and name of files opened were saved in 1.9.4. But in 1.9.5 only the directory path is saved, the file name is missing, so you cannot open the file again using the Recent Files list.

**Comment by snakefoot** [comment]
Thank you for reporting this. I have reproduced and fixed the bug. The fix will be included in next release.

**Comment by snakefoot** [comment]
Version 1.9.6 have been released.

**Comment by burekas7** [comment]
Still the same with 1.9.6 as described.

**Comment by snakefoot** [comment]
@burekas7 Remember to check "Save in Windows Registry"

![image](https://user-images.githubusercontent.com/11509660/71201811-183abf80-229b-11ea-913d-fdca39f4ae3a.png)
