### ISSUE TITLE
Support for Services on remote computers

### ISSUE THREAD

**Issue by Sordalong** [snakefoot/snaketail-net#133]
Hi, 
I'm using SnakeTail to observe the log Files of a Service on 4 diffrent Computers. Works brilliantly. I would love to have the ability to not only restart the service on the local computer, but also on the remote pcs? Is this possible, or could it be coded in?
Thanks a lot for the great Program

**Comment by snakefoot** [comment]
Version 1.9.6 have been released. Tried adding support for services on remote machines.

When you get the time, then please tell if it works.
