### ISSUE TITLE
Wrong file name for SnakeTail.v1.9.6.x86.msi

### ISSUE THREAD

**Issue by issaclin32** [snakefoot/snaketail-net#137]
The content of it is `v.1.9.6`, but the file name remains at `v1.9.5`.

https://github.com/snakefoot/snaketail-net/releases/tag/1.9.6

**Comment by snakefoot** [comment]
Oops. Thank you for telling. Will fix


Sent from my Sony Xperia


---- issaclin32 wrote ----


The content of it is v.1.9.6, but the file name remains at v1.9.5.

https://github.com/snakefoot/snaketail-net/releases/tag/1.9.6

**Comment by snakefoot** [comment]
Updated the release
