### ISSUE TITLE
Unicode display

### ISSUE THREAD

**Issue by gstar42** [snakefoot/snaketail-net#138]
It is unable to display French properly

Aucun Ã©vÃ©nement de connexion nâ€™a Ã©tÃ© signalÃ© pendant cette pÃ©riode      
should be
Aucun événement de connexion n’a été signalé pendant cette période

**Comment by snakefoot** [comment]
What encoding are you using for the file?

Does the encoding include a BOM?

Have you tried changing the encoding to UTF8?

**Comment by gstar42** [comment]
Notepad shows it as UTF-8. It does not have a BOM.


________________________________

**Comment by snakefoot** [comment]
SnakeTail loads by default the file with the default ansi-encoding of the operation system.

You can place an xml-file next to SnakeTail.exe to load all files as UTF8:
- Open a single file
- Change the encoding manual to UTF8 (using options)
- Save the session as SnakeTail.xml and place it next to the SnakeTail.exe-application.

See also: http://snakenest.com/2011/snaketail-ver-1-3-released/
