### ISSUE TITLE
Problem with window design: View Options... -> Configure View

### ISSUE THREAD

**Issue by burekas7** [snakefoot/snaketail-net#140]
The grid and the buttons are not placed well in the last version 1.9.6

In version 1.9.5 (The correct):
![image](https://user-images.githubusercontent.com/13424257/71179332-9fc30700-2278-11ea-8043-3fb46ab666d2.png)

In the last version 1.9.6:
![image](https://user-images.githubusercontent.com/13424257/71179473-e7499300-2278-11ea-9e4b-6283def53e20.png)

**Comment by burekas7** [comment]
And by the way, a small question:
Where this configure view is saved? In the registry or in a file?
Where is it loaded from?

Thanks.

**Comment by snakefoot** [comment]
The configuration is save together with the session. You can save a default session-file here:

http://snakenest.com/2011/snaketail-ver-1-3-released/

**Comment by snakefoot** [comment]
Thanks for reporting this bug. Will fix it.

**Comment by burekas7** [comment]
> The configuration is save together with the session. You can save a default session-file here:
> 
> http://snakenest.com/2011/snaketail-ver-1-3-released/

Thanks, I found my file here:
C:\ProgramData\SnakeTail

I think that instead of:
Common AppData/SnakeTail/SnakeTail.xml

You should change it to:
C:\ProgramData\SnakeTail\SnakeTail.xml
(Because 'Common' is not so clear where is it, which is => C:\ProgramData )

In the Current User there weren't folders with SnakeTail, 
and also, the file wasn't in the Application folder.

**Comment by snakefoot** [comment]
The blog-post was written 8 years ago. New operating systems have probably arrived since then :)

**Comment by xdmtk** [comment]
Also seeing this on my machine as well. Glad to see responsiveness to the issue. 
![2019-12-25 14_09_21-Configure View](https://user-images.githubusercontent.com/36802059/71450932-6549e600-2720-11ea-87e8-08a0935d50d5.png)

**Comment by snakefoot** [comment]
Version 1.9.7 has been released: https://github.com/snakefoot/snaketail-net/releases/tag/1.9.7
