### ISSUE TITLE
Bug: Recent Files isn't saved

### ISSUE THREAD

**Issue by burekas7** [snakefoot/snaketail-net#141]
It has already happened since 1.9.5:
Opening a file.
Go to File -> Recent Files
The file is there.
Close the program.
Open the program again.
Go to File -> Recenet Files.
The last recent file isn't there, is shows None.

On previous versions the recent files were kept.

Thanks.

**Comment by snakefoot** [comment]
Remember to check "Save in Windows Registry" (Checkbox menu-item in "Recent Files")

**Comment by burekas7** [comment]
@snakefoot 
Ok, you right, I forgot.
But why does it save only the directory path and not the entire path include the filename?

**Comment by snakefoot** [comment]
There was a bug in ver. 1.9.5 that is fixed in ver. 1.9.6

**Comment by burekas7** [comment]
Yes, my mistake, I have checked it with 1.9.5.

It's ok with 1.9.6

Thank you.
Great and very useful app!
