### ISSUE TITLE
Default session to open on startup

### ISSUE THREAD

**Issue by adevaykin** [snakefoot/snaketail-net#145]
It would be great to open a particular "default" session on program startup. Or allow specifying it via a CLI argument.

Thanks for the great tool!

**Comment by snakefoot** [comment]
Believe you can save your session to an xml-file, and then make a windows-shortcut-lnk file to the snaketail-application where you give the path to the xml-file.

**Comment by adevaykin** [comment]
That's a good idea! Thank you!
