### ISSUE TITLE
Add option to export Bookmarks features

### ISSUE THREAD

**Issue by GaikwadPratik** [snakefoot/snaketail-net#146]
This is not a bug but a feature request

Nice utility to have in the belt

Currently you can add a bookmark(color filters, etc) on one machine. Can you please add a way to export them from one machine and import it on another? Currently I have to do this manually on every computer that I use for development.

![image](https://user-images.githubusercontent.com/5595263/79214314-a291cb00-7e18-11ea-8f5d-1676bd7cb964.png)

**Comment by snakefoot** [comment]
SnakeTail will apply the default session settings when opening new files. You can just xcopy the session-settings to the machine you like. See also: https://github.com/snakefoot/snaketail-net/issues/106#issuecomment-274929653
