### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by da4089** [snakefoot/snaketail-net#154]
It'd be great to have a "dark mode" theme option for SnakeTail.  Did I miss an existsing way of doing this?

**Comment by da4089** [comment]
Ah, yes, I did: Edit / View Options ...

**Comment by PwrSrg** [comment]
+1 for **Dark Mode**!  I love the **_simplicity_** of SnakeTail, but the Windows '95 theme is **BLINDING**. ☀️🙃
