### ISSUE TITLE
No CMD way?

### ISSUE THREAD

**Issue by Guardian820** [snakefoot/snaketail-net#155]
Please add full support for command line. There is a mention of this feature on the website:

"Save and load entire window session. Can load session file at startup when given as command line parameter."

But where is the documentation and explanation of how to do this just using only command line?

**Comment by snakefoot** [comment]
You just provide the session-file-path as input-argument to the snaketail-application, when running from command-line (It will recognize as session-file by its `xml`-file-extension).

You can also create a link-shortcut to the snaketail-application, and provide the input-argument there. Either a session-xml-file or a specific log-file-txt.

**Comment by Guardian820** [comment]
Very simple, thanks!
