### ISSUE TITLE
What does Display Tab icon on log change do?

### ISSUE THREAD

**Issue by hspindel** [snakefoot/snaketail-net#158]
In Edit/Options, there is a settable option for "Display tab icon on log change".

I was hoping that setting this would cause the watched logfile title bar to change its icon when new log info arrives.  But I don't see any changes in the icon when new log info arrives.  What does this setting do?

I also tried adding an icon file to the Window Icon field in the options.  What does this do?

What is the expected format of the icon file?

**Comment by snakefoot** [comment]
`"Display tab icon on log change"` only works when having multiple tabs open, where tabs not in focus will get icon on log-change

**Comment by hspindel** [comment]
Thank you for the response.

I have multiple tabs open, but do not see any icon change when the log changes.

What does the Window Icon field do?

**Comment by snakefoot** [comment]
> I have multiple tabs open, but do not see any icon change when the log changes.

Works on my machine

> What does the `Window Icon` field do?

Point it to an application-exe-file, and it will show the application-icon for the log-tab

**Comment by hspindel** [comment]
> > I have multiple tabs open, but do not see any icon change when the log changes.
> 
> Works on my machine

Okay, thanks for the response.  Maybe I'm looking in the wrong place?  I'm hoping the icon for the individual log file would change to indicate that the log file changed?

> 
> > What does the `Window Icon` field do?
> 
> Point it to an application-exe-file, and it will show the application-icon for the log-tab

Okay.  Not particularly useful in my case because there are no associated applications.  The log files are coming from routers and switches.

**Comment by snakefoot** [comment]
You need to configure `"Display tab icon on log change"` for each tab. This is how it looks on my machine (Green icon):

![image](https://user-images.githubusercontent.com/11509660/219766155-5088cf24-9672-4d17-8e70-f9ecf0a4a58a.png)

Recall that "Keyword" with "Alert Highlight" will trigger different icon.

**Comment by hspindel** [comment]
Thank you for the photo.  That helped a lot.  I needed to click on Window/Show Tabs to make my screen look like yours.

**Comment by snakefoot** [comment]
Closing question as answered due to inactivity.
