### ISSUE TITLE
File menu keyboard shortcuts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [snakefoot/snaketail-net#77]
```
Hello,
I would very much like some keyboard shortcuts in the File menu, primarily for 
open.

I've added these myself in an svn checkout, with my patch attached if you're 
interested.

```

Original issue reported on code.google.com by `andrewle...@gmail.com` on 3 Oct 2014 at 3:27

Attachments:
* [FileMenuShortcuts.patch](https://storage.googleapis.com/google-code-attachments/snaketail-net/issue-77/comment-0/FileMenuShortcuts.patch)

**Comment by snakefoot** [comment]
Released ver. 1.9.1
