### ISSUE TITLE
Mark text in a line

### ISSUE THREAD

**Issue by ghuacc** [snakefoot/snaketail-net#96]
Marking e.g. an IP address or a word in a line does not work like in most other editors.
I'd propose a **double-click** to mark a **word** between space signs, and a **triple-click** for a **whole line**, similar to Notepad++.

**Comment by ferpega** [comment]
I would like to be able to select/copy text from the line and not the whole line.

**Comment by UselessGuru** [comment]
Second this. This is something I really miss in this very useful program. 👍

**Comment by snakefoot** [comment]
Closing as duplicate of #60
