### ISSUE TITLE
Shortcut for Open File [Ctrl+O] missing

### ISSUE THREAD

**Issue by mfarooq7897** [snakefoot/snaketail-net#99]
Hi Folks
Thanks for your service and making this tool a reality. 

I would like to suggest a basic improvement to the existing tool. I find that the one cannot open files using keyboard shortcut. You have to go to Files, and then click Open File... to do that. 

When can we expect an update that fixes this?

Thanks

**Comment by meskobalazs** [comment]
Sent a PR for this #116

**Comment by snakefoot** [comment]
Fixed with Version 1.9.5
